### ISSUE TITLE
running "adb-wifi" (raspberry) but nothing happens

### ISSUE THREAD

**Issue by incline02** [extmkv/ADB-Wifi#11]
When I interrupt the process, I get this

```
pi@raspberrypi:~ $ adb-wifi
Traceback (most recent call last):
  File "/usr/local/bin/adb-wifi", line 71, in <module>
    devices = getNetworkDevices()
  File "/usr/local/bin/adb-wifi", line 56, in getNetworkDevices
    hosts = nm.scan(
  File "/usr/local/lib/python3.9/dist-packages/nmap/nmap.py", line 275, in scan
    (self._nmap_last_output, nmap_err) = p.communicate()
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1981, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

**Comment by incline02** [comment]
I decided to kill adb server and start adb wifi instead
```
pi@raspberrypi:~ $ adb kill-server
pi@raspberrypi:~ $ adb-wifi
* daemon not running; starting now at tcp:5037
* daemon started successfully
Detected new device to connect: 192.168.1.117
Connected to 192.168.1.117
Detected new device to connect: 192.168.1.117
Connected to 192.168.1.117
```

It works but is it supposed to stay "floating" until I interrupt it? 

also, how do I make it start on boot? I tried `sudo systemctl enable adb-wifi`
But I get `Failed to enable unit: Unit file adb-wifi.service does not exist.`
